## Exercícios de Depuração e Teste de Algorimos


### Exemplo 1 -

Depure em uma tabela o programa a seguir:

a) mostre a evolução das variáveis de posição ou contagem (total_de_elementos e posicao_atual);
b) mostre a saída de do programa em em toda evolução do laço FOR

```python
dias_semana = [ "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado", "Domingo" ]

total_de_elementos = len(dias_semana)

posicao_atual = 0

print("Dias da semana:\n")

for ( posicao_atual ) in range( total_de_elementos ):
    print( dias_semana[posicao_atual] )

```

Depuração manual

```text
+-----------+----------------------+------------------+------------------+
| Iteração  | total_de_elementos   | posicao_atual    | Valor Acessado   |
+-----------+----------------------+------------------+------------------+
| Inicial   | 7                    | 0                | -                |
+-----------+----------------------+------------------+------------------+
| 1         | 7                    | 0                | Segunda-feira    |
| 2         | 7                    | 1                | Terça-feira      |
| 3         | 7                    | 2                | Quarta-feira     |
| 4         | 7                    | 3                | Quinta-feira     |
| 5         | 7                    | 4                | Sexta-feira      |
| 6         | 7                    | 5                | Sábado           |
| 7         | 7                    | 6                | Domingo          |
+-----------+----------------------+------------------+------------------+
```






### Exemplo 2 -
Implemente um programa em Python que:
- Crie uma matriz bidimensional (lista de listas) com 3 linhas e 4 colunas, contendo valores inteiros sequenciais (por exemplo: de 1 a 12).
- Utilize estruturas de repetição (for) para percorrer todos os elementos da matriz.
- Exiba os valores da matriz organizados em formato tabular (3x4), respeitando linhas e colunas.

```python
matriz = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

total_de_linhas  = len(matriz)
total_de_colunas = len(matriz[0])

linha_atual  = 0
coluna_atual = 0

print("Matriz 3x4:\n")

for linha_atual in range(total_de_linhas):   
    for coluna_atual in range(total_de_colunas):
        print(matriz[linha_atual][coluna_atual], end="\t")
    print("\n")
```

Depuração manual

```text
+----------+--------+---------+-------+--------+----------------+
| Iteração | total  | total   | linha | coluna | Valor Impresso |
|          | linhas | colunas | atual | atual  |                |
+----------+--------+---------+-------+--------+----------------+
| Inicio   | 3      | 4       | 0     | 0      | --             |
+----------+--------+---------+-------+--------+----------------+
| 1        | 3      | 4       | 0     | 0      | 1              |
+----------+--------+---------+-------+--------+----------------+
| 2        | 3      | 4       | 0     | 1      | 2              |
+----------+--------+---------+-------+--------+----------------+
| 3        | 3      | 4       | 0     | 2      | 3              |
+----------+--------+---------+-------+--------+----------------+
| 4        | 3      | 4       | 0     | 3      | 4              |
+----------+--------+---------+-------+--------+----------------+
| 5        | 3      | 4       | 1     | 0      | 5              |
+----------+--------+---------+-------+--------+----------------+
| 6        | 3      | 4       | 1     | 1      | 6              |
+----------+--------+---------+-------+--------+----------------+
| 7        | 3      | 4       | 1     | 2      | 7              |
+----------+--------+---------+-------+--------+----------------+
| 8        | 3      | 4       | 1     | 3      | 8              |
+----------+--------+---------+-------+--------+----------------+
| 9        | 3      | 4       | 2     | 0      | 9              |
+----------+--------+---------+-------+--------+----------------+
| 10       | 3      | 4       | 2     | 1      | 10             |
+----------+--------+---------+-------+--------+----------------+
| 11       | 3      | 4       | 2     | 2      | 11             |
+----------+--------+---------+-------+--------+----------------+
| 12       | 3      | 4       | 2     | 3      | 12             |
+----------+--------+---------+-------+--------+----------------+
```


Exercício 1 -


Considere o modelo apresentado em aula para percorrer uma lista utilizando índice.

Agora, elabore um programa em Python que:

- Crie uma lista chamada estados_brasil contendo as 27 siglas das unidades federativas do Brasil:
AC, AL, AP, AM, BA, CE, DF, ES, GO, MA, MT, MS, MG, PA, PB, PR, PE, PI, RJ, RN, RS, RO, RR, SC, SP, SE, TO
- Calcule o total de elementos da lista utilizando a função len().
- Utilize uma variável de controle chamada posicao_atual, iniciando com valor 0.
- Utilize uma estrutura de repetição while para percorrer a lista.
- Imprima cada sigla em uma linha.


```python

estados_brasil = [
    "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO",
    "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI",
    "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"
]

_________________ = len(__________________)

_________________ = 0

print("_____________________")

while _______________ < _________________ :
    print( _________________[_______________])
    _____________ = ___________________ + 1

```

```TEXT


```








### Respostas

#### Exercício 1


```python

estados_brasil = [
    "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO",
    "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI",
    "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"
]

total_de_elementos = len(estados_brasil)

posicao_atual = 0

print("Estados do Brasil:\n")

while posicao_atual < total_de_elementos:
    print(estados_brasil[posicao_atual])
    posicao_atual = posicao_atual + 1
```


```TEXT

+----------+-----------+---------+----------------+
| Iteração | total     | Posicao | Valor Impresso |
|          | elementos | atual   |                |
+----------+-----------+---------+----------------+
| Inicio   | C         | 0       | --             |
+----------+-----------+---------+----------------+
| 1        | 27        | 1       | AC             |
+----------+-----------+---------+----------------+
| 2        | 27        | 2       | AL             |
+----------+-----------+---------+----------------+
| 3        | 27        | 3       | AP             |
+----------+-----------+---------+----------------+
| 4        | 27        | 4       | AM             |
+----------+-----------+---------+----------------+
| 5        | 27        | 5       | BA             |
+----------+-----------+---------+----------------+
| 6        | 27        | 6       | CE             |
+----------+-----------+---------+----------------+
| 7        | 27        | 7       | DF             |
+----------+-----------+---------+----------------+
| 8        | 27        | 8       | ES             |
+----------+-----------+---------+----------------+
| 9        | 27        | 9       | GO             |
+----------+-----------+---------+----------------+
| 10       | 27        | 10      | MA             |
+----------+-----------+---------+----------------+
| 11       | 27        | 11      | MT             |
+----------+-----------+---------+----------------+
| 12       | 27        | 12      | MS             |
+----------+-----------+---------+----------------+
| 13       | 27        | 13      | MG             |
+----------+-----------+---------+----------------+
| 14       | 27        | 14      | PA             |
+----------+-----------+---------+----------------+
| 15       | 27        | 15      | PB             |
+----------+-----------+---------+----------------+
| 16       | 27        | 16      | PR             |
+----------+-----------+---------+----------------+
| 17       | 27        | 17      | PE             |
+----------+-----------+---------+----------------+
| 18       | 27        | 18      | PI             |
+----------+-----------+---------+----------------+
| 19       | 27        | 19      | RJ             |
+----------+-----------+---------+----------------+
| 20       | 27        | 20      | RN             |
+----------+-----------+---------+----------------+
| 21       | 27        | 21      | RS             |
+----------+-----------+---------+----------------+
| 22       | 27        | 22      | RO             |
+----------+-----------+---------+----------------+
| 23       | 27        | 23      | RR             |
+----------+-----------+---------+----------------+
| 24       | 27        | 24      | SC             |
+----------+-----------+---------+----------------+
| 25       | 27        | 25      | SP             |
+----------+-----------+---------+----------------+
| 26       | 27        | 26      | SE             |
+----------+-----------+---------+----------------+
| 27       | 27        | 27      | TO             |
+----------+-----------+---------+----------------+
```




